apiVersion: v1
kind: Service
metadata:
  name: database  # Este nombre debe coincidir con el que estás usando en DATABASE_URL
spec:
  selector:
    app: database  # Asegúrate de que coincida con la etiqueta del pod de la base de datos
  ports:
    - protocol: TCP
      port: 5432  # El puerto expuesto por el servicio
      targetPort: 5432  # El puerto en el que la base de datos está escuchando
