name: Deploy to Cluster
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Database image
      - name: Build and push Database image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/database:latest

      # Build and push Web App image
      - name: Build and push Web App image
        uses: docker/build-push-action@v3
        with:
          context: ./appweb
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/appweb:latest

      # Build and push Proxy image
      - name: Build and push Proxy image
        uses: docker/build-push-action@v3
        with:
          context: ./proxy
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/proxy:latest


